services:
  - type: web
    name: the-silicon-citadel
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn silicon.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "the-silicon-citadel.onrender.com"
      - key: SECRET_KEY
        generateValue: true
