# Generated by Django 6.0.2 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', 'Miembro'), ('editor', 'Editor'), ('admin', 'Administrador')], default='member', max_length=20),
        ),
    ]
