# Generated by Django 6.0.2 on 2026-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', 'Miembro'), ('vigilante', '👁️ Vigilante del Portón'), ('guardian', '🛡️ Guardian de la Muralla'), ('capitan', '🔨 Capitán del Martillo'), ('ancianos', '📜 Consejo de Ancianos'), ('rey', '👑 Rey bajo la Montaña')], default='member', max_length=20),
        ),
    ]
