# Generated by Django 6.0.2 on 2026-02-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_portfolio_subscriber_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Laptops & Portátiles', 'Laptops & Portátiles'), ('Tablets & iPads', 'Tablets & iPads'), ('Consolas de Forja', 'Consolas de Forja'), ('PC Desktop', 'PC Desktop'), ('Componentes Core', 'Componentes Core'), ('Periféricos & Accesorios', 'Periféricos & Accesorios'), ('Taller de Reparación', 'Taller de Reparación'), ('Redes & Enlaces', 'Redes & Enlaces'), ('Alquimia de Software', 'Alquimia de Software'), ('Artefactos & Gadgets', 'Artefactos & Gadgets')], default='General', max_length=50),
        ),
    ]
