# Generated by Django 6.0.2 on 2026-02-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_newsitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbs/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (ej: desde Google Images, Imgur, etc.)', max_length=500, null=True),
        ),
    ]
