# Generated by Django 6.0.2 on 2026-02-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blogpost_image_blogpost_image_url_newsitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descripción corta para listas (máx 300 caracteres)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descripción corta para la lista de actualizaciones (máx 300 caracteres)', max_length=300, null=True),
        ),
    ]
